[package]
name = "rust_exercises"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sub_arr"
path = "src/sub_arr.rs"

[[bin]]
name = "check_char"
path = "src/check_char.rs"

[dependencies]
